### ISSUE TITLE
[Bug]: Weird arrow behavior when using Explosive Tip Enchantment

### ISSUE THREAD

**Issue by Jouto55** [SiverDX/additional_enchantments#2]
When using the Explosive Tip enchantment, the arrows behave weirdly.

https://github.com/SiverDX/additional_enchantments/assets/148708399/188bf04a-2f7b-4934-81fd-40135854b262

This behavior also extends to Tridents, and Crossbows.

Mods:
	- additional_enchantments 0.3.3
	- do_a_barrel_roll 3.5.0+1.20.1
	- easyanvils 8.0.1
	- easymagic 8.0.1
	- embeddium 0.2.18+mc1.20.1
	- embeddiumplus 1.2.3
	- enchantinginfuser 8.0.2
	- forge 47.2.19
	- geckolib 4.4
	- minecraft 1.20.1
	- mixinextras 0.3.5
	- oculus 1.6.13
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.14
	- reeses_sodium_options 1.0.4
	- rubidium 0.7.1
	- sculkhorde 1.20.1-0.8.4
	- textrues_embeddium_options 0.1.3+mc1.20.1
	- universalenchants 8.0.0
	- xaerominimap 23.9.3
	- xaeroworldmap 1.37.2

Minecraft Version: 1.20.1
Mod Loader: Forge 47.2.19
OS: Windows 11

**Comment by SiverDX** [comment]
seems to be due to a difference in forge & neoforge codebase
this mod is developed using neforoge as basis for 1.20+

not sure if this will be addressed

**Comment by Jouto55** [comment]
> seems to be due to a difference in forge & neoforge codebase this mod is developed using neoforge as basis for 1.20+
> 
> not sure if this will be addressed

Didn't cpw say that NeoForge 1.20.1 was gonna be compatible with 1.20.1 Forge?

Are there major differences in 1.20.1 NeoForge that would cause difficulty in fixing this bug?

**Comment by SiverDX** [comment]
https://github.com/PaintNinja/MinecraftForge/commit/2f229c5bb1dd6c8db70e3daac2aad05948ad12a8

It's this to be exact

**Comment by Jouto55** [comment]
> [PaintNinja/MinecraftForge@2f229c5](https://github.com/PaintNinja/MinecraftForge/commit/2f229c5bb1dd6c8db70e3daac2aad05948ad12a8)
> 
> It's this to be exact
> 
> NeoForge did not do this change: https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/entity/projectile/AbstractArrow.java.patch

Hmm. Given that NeoForge is now diverging from Forge, the best thing to do at this point is to either.

A. Take the easy route and just ignore the bug.

B. Split the mod into NeoForge and Forge versions so the bug is fixed on the Forge side of things.

**Comment by SiverDX** [comment]
well there is this https://github.com/neoforged/NeoForge/pull/23

since the forge implementation regressed when doing this change (not considering blocks and only caring about entity hits) it wouldn't be much use for me atm

will probably have to do a mixin which only loads for forge

**Comment by SiverDX** [comment]
fixed in https://www.curseforge.com/minecraft/mc-mods/additional-enchantments/files/5059564

**Comment by Jouto55** [comment]
Tested the mod with fix, arrows now behave normally. 👍
