### ISSUE TITLE
I don't know how to solve it

### ISSUE THREAD

**Issue by 4234sdsadqrwrwer** [SiverDX/additional_enchantments#3]
"I want to remove the Iron Golem from the Shatter enchantment, but I don't know where to modify it. Also, how to write the disabling potion effects for Tipped, and in which file.

**Comment by SiverDX** [comment]
the iron golem should already be blacklisted: 
https://github.com/SiverDX/additional_enchantments/blob/877a3524efdb5862108e94bfb074a2df5452638a/src/generated/resources/data/additional_enchantments/tags/entity_types/shatter_aoe_blacklist.json#L1-L6

but it's not checked atm, will fix that

tipped blacklist is here:
https://github.com/SiverDX/additional_enchantments/blob/877a3524efdb5862108e94bfb074a2df5452638a/src/generated/resources/data/additional_enchantments/tags/mob_effect/tipped_blacklist.json#L1-L3

To change either you'll have to use a datapack (https://minecraft.wiki/w/Data_pack) to modify the tags (https://minecraft.wiki/w/Tag)

**Comment by 4234sdsadqrwrwer** [comment]
Thanks, but I meant removing the Iron Golem from the blacklist

**Comment by SiverDX** [comment]
That is still done through a datapack
There should be enough tutorials around on how to do this since it's a vanilla feature

The corresponding file is `/additional_enchantments/tags/entity_types/shatter_aoe_blacklist.json` with the content:
```json
{
  "replace": true,
  "values": [
    "minecraft:villager"
  ]
}
```
(Note that in this case the tag will only contain the entries you specify here)

I don't know if 1.19.2 has this but in 1.20.1 you can explicitly remove things without having to re-specify every other entry

```json
{
  "remove": [
    "minecraft:iron_golem"
  ]
}
```

**Comment by 4234sdsadqrwrwer** [comment]
I am very sorry, I shouldn't bother you further, but I found that the data pack I wrote is not working, although it should be correct. Here are the details:

Added MODs: Jade, additional_enchantments Game version: 1.20.1 Data pack path: additional_enchantments/data/additional_enchantments/tags/mob_effect/tipped_blacklist Data pack content: { 'replace': true, 'values': [ 'minecraft:slowness' ] }



![dsdad](https://github.com/user-attachments/assets/9370490d-8133-4437-83e4-3468b32ddd73)

**Comment by SiverDX** [comment]
Seems like there was an additional issue regarding how tags are handled
It's fixed in the new version currently uploading

Tested it with this:
[some_datapack.zip](https://github.com/user-attachments/files/17441075/some_datapack.zip)

**Comment by 4234sdsadqrwrwer** [comment]
Now the blacklist can be correctly set, and it works as expected. After such a long period of testing, it turned out that the issue was surprisingly due to a tag error.

**Comment by 4234sdsadqrwrwer** [comment]
Now the blacklist can be correctly set, and it works as expected
